#!/usr/bin/env python
# encofing:utf-8
import os
from time import sleep
os.system("apt-get install figlet")
os.system("clear")
os.system("python -m pip install colorama")
os.system("apt-get install cowsay")
import colorama
from colorama import Fore, Back, Style
colorama.init()
os.system("apt-get install figlet")
os.system("clear")
us = input("Sena'nın Uğurlu Sayısı >>> ")
if(us=="3"):
	os.system("clear")
	print(Fore.YELLOW)
	os.system("figlet Giris Basarili")
	print(Fore.BLUE)
	print("Sena Hakkında Aşağıdaki Bilgilerden Hangisine Sahipsin")
	print(Fore.RED)
	print("""
	1 >>> Sena'nın Göz Rengi                     | 10 Puan
	2 >>> Sena'nın En Sevdiği Oyun               | 15 Puan
	3 >>> Sena'nın İnstagram Hesabının İsmi      | 05 Puan
	
	""")
	s1 = input("Cevap Vermek İstediğiniz Soru: ")
	if(s1=="1"):        	
 		s12 = input("Cevabınız >>> ")
 		if(s12=="Kahverengi"):
 				print(Fore.YELLOW)
 				print("""
 				Soru 1
 				    Sena'nın En İnstagram Kullanıcı Adı Nedir?
 				    
 				    A) rocklee
 				    B) nssensnku
 				    C) nshihakuu
 				    D) sena_snakuu
 				
 				""")
 				s2 = input("                        Cevap: ")
 				if(s2=="C"):
 					print(Fore.YELLOW)
 					print("+20 Puan")
 					a = 20
 				else:
 					print("-20 Puan")
 					
 					    
 		
 	 
 				
else:
      print("Yanlış Cevap")

